pipeline {
    agent {
        label 'php-agent'
    }

    stages {
        stage('Install Dependencies') {
            steps {
                echo 'Preparing project...'
                sh 'php -v'
            }
        }

        stage('Run Tests') {
            steps {
                echo 'Running tests...'
                sh 'php tests/helpers_test.php'
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed.'
        }
        success {
            echo 'All stages completed successfully!'
        }
        failure {
            echo 'Errors detected in the pipeline.'
        }
    }
}
