pipeline {
    agent {
        label 'php-agent'
    }

    stages {
        stage('Install Dependencies') {
            steps {
                echo 'Preparing project...'
                dir('lab04/recipe-book') {
                    sh 'composer install'
                }
            }
        }

        stage('Test') {
            steps {
                dir('lab04/recipe-book') {
                    // запуск тестов
                    sh './vendor/bin/phpunit --testdox'
                    // либо команда, которая у тебя реально запускает тесты
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed.'
        }
        success {
            echo 'All stages completed successfully!'
        }
        failure {
            echo 'Errors detected in the pipeline.'
        }
    }
}
