pipeline {
    agent {
        label 'php-agent'
    }

    stages {        
        stage('Install Dependencies') {
            steps {
                echo 'Preparing project...'
                // установка зависимостей проекта
                sh 'composer install'
            }
        }
        
        stage('Test') {
            steps {
                echo 'Running tests...'
                // запуск юнит-тестов
                sh './vendor/bin/phpunit --testdox'
            }
        }
    }
    
    post {
        always {
            echo 'Pipeline completed.'
        }
        success {
            echo 'All stages completed successfully!'
        }
        failure {
            echo 'Errors detected in the pipeline.'
        }
    }
}
