# Ansible-агент на базе Ubuntu
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# Устанавливаем SSH-сервер, Python, Ansible и Java
RUN apt-get update && apt-get install -y --no-install-recommends \
    openssh-server \
    python3 \
    python3-pip \
    ansible \
    git \
    openjdk-21-jre-headless \
    && rm -rf /var/lib/apt/lists/*

# Создаём пользователя ansible
RUN useradd -m -d /home/ansible -s /bin/bash ansible && \
    mkdir -p /home/ansible/.ssh && \
    chown -R ansible:ansible /home/ansible/.ssh

# Готовим SSH-сервер
RUN mkdir -p /var/run/sshd

# Публичный ключ Jenkins -> Ansible-агент
# jenkins_ansible_ssh_key.pub будет сгенерирован в разделе 3.2
COPY secrets/jenkins_ansible_ssh_key.pub /home/ansible/.ssh/authorized_keys

RUN chown ansible:ansible /home/ansible/.ssh/authorized_keys && \
    chmod 700 /home/ansible/.ssh && \
    chmod 600 /home/ansible/.ssh/authorized_keys

# Ключи Ansible-агента для подключения к тестовому серверу (раздел 3.3)
COPY secrets/ansible_test_ssh_key /home/ansible/.ssh/id_ed25519
COPY secrets/ansible_test_ssh_key.pub /home/ansible/.ssh/id_ed25519.pub

RUN chown ansible:ansible /home/ansible/.ssh/id_ed25519* && \
    chmod 600 /home/ansible/.ssh/id_ed25519

# Папка для будущих настроек Ansible (inventory, ansible.cfg)
RUN mkdir -p /etc/ansible && chown -R ansible:ansible /etc/ansible

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D", "-e"]
